name: safeloan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  web: ^0.4.0
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_auth: ^4.17.8
  http: ^1.2.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.1+1
  fl_chart: ^0.68.0
  intl: ^0.19.0
  image_picker: ^1.0.8
  badges: ^3.1.2
  youtube_player_flutter: ^9.0.1
  google_nav_bar: ^5.0.6
  url_launcher: ^6.3.0
  chat_bubbles: 1.6.0
  font_awesome_flutter: ^10.7.0
  loading_animation_widget: ^1.2.1
  google_fonts: 6.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

