// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOvtOBEdfMuGZozGg0CtWiRgEI_uxJ45o',
    appId: '1:506463094814:web:c27c126e8365001fa4460f',
    messagingSenderId: '506463094814',
    projectId: 'safe-loan-1ea9e',
    authDomain: 'safe-loan-1ea9e.firebaseapp.com',
    storageBucket: 'safe-loan-1ea9e.appspot.com',
    measurementId: 'G-KGMZXQMXEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUZzMc8DREUaTKPtFLnhwXJKAMQqMWPgA',
    appId: '1:506463094814:android:052e6ad2d2f61521a4460f',
    messagingSenderId: '506463094814',
    projectId: 'safe-loan-1ea9e',
    storageBucket: 'safe-loan-1ea9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCanlBuwAn-rT4OroPsEACail2UNEeSDt4',
    appId: '1:506463094814:ios:c1bac9a647b2661da4460f',
    messagingSenderId: '506463094814',
    projectId: 'safe-loan-1ea9e',
    storageBucket: 'safe-loan-1ea9e.appspot.com',
    iosBundleId: 'com.safeloan.safeloan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCanlBuwAn-rT4OroPsEACail2UNEeSDt4',
    appId: '1:506463094814:ios:c1bac9a647b2661da4460f',
    messagingSenderId: '506463094814',
    projectId: 'safe-loan-1ea9e',
    storageBucket: 'safe-loan-1ea9e.appspot.com',
    iosBundleId: 'com.safeloan.safeloan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOvtOBEdfMuGZozGg0CtWiRgEI_uxJ45o',
    appId: '1:506463094814:web:b634183f7debe1d6a4460f',
    messagingSenderId: '506463094814',
    projectId: 'safe-loan-1ea9e',
    authDomain: 'safe-loan-1ea9e.firebaseapp.com',
    storageBucket: 'safe-loan-1ea9e.appspot.com',
    measurementId: 'G-K2C435MLS2',
  );
}
